### ISSUE TITLE
ERROR 422 (Invalid request.  For 'properties/body', nil is not a string.)

### ISSUE THREAD

**Issue by jcurlier** [release-it/release-it#1014] opened 2023-06-14 09:48 UTC
Version: 15.11.0

If I release my nodeJS project twice, the second time it fails:

```
> @aura/content-service@2.223.0 release
> npx release-it

🚀 Let's release @aura/content-service (currently at 2.223.0)

Empty changelog

? Select increment (next version): patch (2.223.1)

Changeset:
 M package-lock.json
 M package.json

? Commit (Release 2.223.1)? Yes

? Tag (v2.223.1)? Yes
? Push? Yes

? Create a release on GitHub (Release 2.223.1)? Yes
ERROR 422 (Invalid request.

For 'properties/body', nil is not a string.)
```

The second release doesn't have any git changes, usually I use such a release to force a restart of the app and a refresh of the cache.

**Comment by christophemorio** [comment] 2023-06-14 13:16
After enable debug https://github.com/release-it/release-it/blob/main/README.md#troubleshooting--debugging, I spot a diff in `body` value.

But did not check by version sticking on **octokit-rest** upgraded dependency https://github.com/octokit/rest.js

## 15.10.3 ok
```
! octokit repos.createRelease "v2.8.3" (v2.8.3)
RELEASE-IT:GITHUB 523: {
  owner: 'Foo',
  repo: 'bar',
  tag_name: 'v2.8.3',
  name: 'v2.8.3',
  body: undefined,
  draft: false,
  prerelease: false,
  generate_release_notes: false
}
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/15.10.3 octokit-rest.js/19.0.7 octokit-core.js/4.2.1 Node.js/17.9.1 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: {
    timeout: 0,
    fetch: [AsyncFunction: fetch],
    hook: [Function: bound bound register]
  },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'Foo',
  repo: 'bar',
  tag_name: 'v2.8.3',
  name: 'v2.8.3',
  draft: false,
  prerelease: false,
  generate_release_notes: false
}
POST /repos/Foo/bar/releases - 201 in 704ms
```

## 15.11.0 (latest) failed
```
! octokit repos.createRelease "v2.8.3" (v2.8.3)
RELEASE-IT:GITHUB 548: {
  owner: 'Foo',
  repo: 'bar',
  tag_name: 'v2.8.3',
  name: 'v2.8.3',
  body: null,
  draft: false,
  prerelease: false,
  generate_release_notes: false
}
request {
  method: 'POST',
  baseUrl: 'https://api.github.com',
  headers: {
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'release-it/15.11.0 octokit-rest.js/19.0.11 octokit-core.js/4.2.1 Node.js/17.9.1 (linux; x64)'
  },
  mediaType: { format: '', previews: [] },
  request: {
    timeout: 0,
    fetch: [AsyncFunction: fetch],
    hook: [Function: bound bound register]
  },
  url: '/repos/{owner}/{repo}/releases',
  owner: 'Foo',
  repo: 'bar',
  tag_name: 'v2.8.3',
  name: 'v2.8.3',
  body: null,
  draft: false,
  prerelease: false,
  generate_release_notes: false
}
POST /repos/Foo/bar/releases - 422 in 256ms
```

**Comment by webpro** [comment] 2023-07-09 18:20
Sorry I'm late to the party, but is this still an issue? I've done a few updates of dependencies in the meantime.

**Comment by jcurlier** [comment] 2023-07-10 21:32
Still happening for me with `16.1.0`

**Comment by aavargasp** [comment] 2023-07-12 21:31
### A little context

I realized that Gitlab returns 422 on the API for `POST /projects/:id/releases` when one or more of the required fields are missing. So I validated my theory trying the API directly then the question is why on **** is data missing?

Then after the 342 time reading the .md files for this, the next line got me thinking
![image](https://github.com/release-it/release-it/assets/42853199/00b1859c-2df7-4681-af4a-7b49f518072e)

**So comparing 2 executions with the debug flag I finally found that the data missing is the tag info that must be on the release**

### The problem


Config `git push` default `.release-it.json`
```
"git": {
    "requireCleanWorkingDir": true,
    "commitMessage": "release v${version}"
  },
```

Detail log on my gitlab ci jo with default `git push`
![default_git_push](https://github.com/release-it/release-it/assets/42853199/d83fabd2-c4c0-4f9a-858c-b6bc1026d2dc)

Config `git push` modified `.release-it.json`
```
"git": {
    "requireCleanWorkingDir": true,
    "commitMessage": "release v${version}",
    "pushArgs": "-o ci.skip"
  },
```
Detail log on my gitlab ci jo with modified`git push` (Missing tag!)
![altered_git_push](https://github.com/release-it/release-it/assets/42853199/dbd1dcca-a5a9-4b9f-88ee-6eeec7f1e25d)


### About the solution

The problem was that I needed to add a pushArg to the final git push before the gitlab release and because of that my argument ovewrites one that is set by default

But the issue is that I assumed that if I needed to add more pushArgs to the `git push` it wouldn't affect the default push or append my args to the default ones (that I didn't know existed)

**Added the default `--follow-tags` and my `-o ci.skip` to the `pushArgs`** 
```
"git": {
    "requireCleanWorkingDir": true,
    "commitMessage": "release v${version}",
    "pushArgs": "--follow-tags -o ci.skip"
  },
```

**Working log with both args !**
![working_git_push](https://github.com/release-it/release-it/assets/42853199/57f7bf7d-27fc-4eb1-b660-101c8b2d1ede)

**Now my release is created correctly because it has the missing tag data**
`Successfully released 0.0.2-beta.7`


PS:
- Sorry for the long post but I think this is really an error that should be fixed in a new version, so I wanted to explain in detail about this.

**Comment by ShaunaGordon** [comment] 2023-10-17 14:07
I'm still getting this on 16.1.5, as well, but oddly enough, aavargasp's solution no longer works for me (it had worked a few months ago, but no longer).

**Comment by seanpoulter** [comment] 2024-03-09 04:33
> Sorry I'm late to the party, but is this still an issue?

Yes. We just saw this on https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8211712054/job/22461024964 using `release-it@17.1.1`. We were testing the pre-release GitHub Workflow and trying to increment the pre-release from `6.3.1-next.0` to `6.3.1-next.1` with no changes.

Let me know if you'd welcome a PR.

At first glance it looks like we'd want to remove `null` from the `body` on line 215. Can anyone help walk me through the downstream impact of that?
https://github.com/release-it/release-it/blob/91b5d2faedd7fc1dd412d463fae75e1feafe36d6/lib/plugin/github/GitHub.js#L208-L215

Since I'm not familiar with the code my proposal would be to:

* Modify the `nock` to return `422 Unprocessable Entity` if `body` is `null`
* Make sure we have a failing test. I can try to reproduce my use case.
* Prevent the body from being `null`

**Comment by webpro** [comment] 2024-05-08 07:23
Feel free to open a PR! I welcome PRs for sure and I'm happy to review. A draft PR is fine and I'm we'll can sort it out.

**Comment by webpro** [comment] 2024-09-11 18:27
Going to close this one. If there's any remaining issues left, your best bet is a PR we can discuss. But new issues are fine too.

**Closed by webpro** 2024-09-11 18:27 UTC

**Comment by tedteng** [comment] 2024-12-10 00:11
The issue still exists. 

```
97 packages are looking for funding
  run `npm fund` for details
Creating Relase with tag v0.124.0
🚀 Let's release xxxx (0.123.0...0.124.0)
Empty changelog
- Git tag
✔ Git tag
- Git push
✔ Git push
- GitHub create release
✖ GitHub create release
ERROR 4[22](https://github.xxx/org/repo/actions/runs/9799094/job/4049413#step:5:23) (Invalid request.

For 'properties/body', nil is not a string. - https://docs.github.com/enterprise-server@3.12/rest/releases/releases#create-a-release)
Error: Process completed with exit code 1.
```

Github action
```
run: |
  npm install -g release-it
  next_ver="v$(release-it minor --release-version)"
  echo "Creating Release with tag $next_ver"
  release-it minor --ci
```

**Comment by webpro** [comment] 2024-12-10 10:55
> your best bet is a PR we can discuss. But new issues are fine too.

A pull request works best, because that allows to understand the issue best and verify it's resolved properly in the environment the bug surfaced.
