### ISSUE TITLE
How to preserve `typings` in package.json?

### ISSUE THREAD

**Issue by zhangciwu** [release-it/release-it#756] opened 2021-04-12 04:02 UTC
Command: `"release-it --no-git --no-npm --preRelease=beta"`
I have this in package.json `"typings": "./index.d.ts",`, but in release pack, it's gone (this `index.d.ts` has disappeared too)

I'm not sure if it's a problem within `release-it`, I searched and got no useful information, so asked here

**Comment by zhangciwu** [comment] 2021-04-12 06:35
Noticed that github release pack is from master branch, not from my working branch

**Comment by webpro** [comment] 2021-04-12 11:46
That's weird. I know release-it only updates the `package.json` file through this command:

```
npm version ${version} --no-git-tag-version
```

Pretty sure this is not something that might be caused by release-it, so I'm going to close this issue.

**Closed by webpro** 2021-04-12 11:46 UTC
