### ISSUE TITLE
Issues with order of operations for changelog and version bump

### ISSUE THREAD

**Issue by mansona** [release-it/release-it#747] opened 2021-03-05 15:17 UTC
Hey folks 👋   I'm just trying to automate my release process on a few of the open-source repos that I manage so that I just need to do a `npm run release` and it does everything that I need it to do with no manual processes. 

But I have a bit of a strange situation 🤔  I'm trying to use auto-changelog (in a similar way to the example https://github.com/release-it/release-it/blob/master/docs/changelog.md#auto-changelog ) and also use github plugin to update the github release page automatically but there seems to be a mismatch of the data. 

I'll paste a copy of the output from my run and explain the issue that I have: 

```
➜  broccoli-static-site-json git:(master) GITHUB_TOKEN=REDACTED npm run release

> broccoli-static-site-json@4.2.1 release
> release-it


🚀 Let's release broccoli-static-site-json (currently at 4.2.1)


Changelog:
Unreleased / 2021-03-05
==================
* Stop erroring with missing folder #53 from @mansona

? Select increment (next version): minor (4.3.0)
✔ npx auto-changelog --template changelog.template --unreleased-only --prepend --load-github-issue-data --github-cache-dir .changelog --package

Changeset:
M CHANGELOG.md
 M package-lock.json
 M package.json

? Publish broccoli-static-site-json to npm? Yes
? Please enter OTP for npm: REDACTED
? Commit (Release 4.3.0)? Yes
? Tag (v4.3.0)? Yes
? Push? Yes
? Create a release on GitHub (Release 4.3.0)? Yes
🔗 https://www.npmjs.com/package/broccoli-static-site-json
🔗 https://github.com/empress/broccoli-static-site-json/releases/tag/v4.3.0
🏁 Done (in 74s.)
```

You can see that the changelog output to stdout has `Unrealeased` as the version number. This is because we need to use the following auto-changelog flag to make sure it includes features that are not released yet: 

```
npx auto-changelog --unreleased-only --stdout 
``` 

And because the changelog step happens before the version bump step it's impossible for auto-changelog to know what the next version is going to be. That's fine because, as you suggest in the documentation, we need to add the `after:bump` hook to actually update the Changelog file: 

```
npx auto-changelog --unreleased-only --prepend --package
```

This now takes the updated version number from the package.json file (updated in the previous step) and names things correctly: 

```
v4.3.0 / 2021-03-05
==================
  * Stop erroring with missing folder #53 from @mansona
```

now when this process continues, the GitHub release step is not using the same data that is making its way into the Changelog **file**. This results in the GitHub release containing the data with `Unreleased` in the title of the release. This is obviously 99% of the way towards what I want, but I would need to edit the GitHub release to update the title to be the correct version which is a bit annoying 😉 

Is this something that we think we can solve? I don't know if it's possible to change the order of steps or if that would have a massive influence on the rest of the system 🤔

**Comment by driiftkiing** [comment] 2021-03-12 09:58
One way would be to provide the github plugin a custom release note:
```
{
  "github": {
    "releaseNotes": "npx auto-changelog --stdout --template changelog.template --starting-version ${version}"
  }
}
```

**Comment by mansona** [comment] 2021-03-12 10:01
oh interesting 🤔  I'll give that a go and see what happens 👍

**Comment by mansona** [comment] 2021-03-23 22:33
So I couldn't get your suggestion to work @driiftkiing I think it was ultimately a problem that was still being caused by the order of operations. 

I did however make a bit of a workaround thanks to your suggestion. Here is my release-it config in full: 

```
module.exports = {
  git: {
    changelog: 'npx auto-changelog --template changelog.template --unreleased-only --stdout',
  },
  hooks: {
    'after:bump': 'npx auto-changelog --template changelog.template --unreleased-only --prepend --package',
  },
  github: {
    release: true,
    releaseNotes: "cat CHANGELOG.md | sed -e '/^$/,$d'"
  }
};
```

The reason for the `git.changelog` config is so that you get a printout of what the changelog is going to be before you have to choose the semver bump type that it will be. This will have `Unreleased` as the version as I said before.

Then the `hooks.after:bump` actually applies the change to the top of the changelog file (this time reading the version info from the newly updated package.json)

Now because releaseNotes runs after the changelog file is actually updated on disk I found a simple **sed** script that extracts all text before the first empty line. This happens to work for me because my changelog template only has gaps **between** versions so I am essentially extracting the last thing that was added to the changelog file and which happens to be the right output that I need. 

This is obviously quite a brittle setup 🙈 and I'm concerned about the portability of this solution to all my open source projects 🤔

**Comment by webpro** [comment] 2021-03-24 20:40
> The reason for the `git.changelog` config is so that you get a printout of what the changelog is going to be before you have to choose the semver bump type that it will be.

This was indeed the idea behind it. The output of the `git.changelog` never updates any file.

> Now because releaseNotes runs after the changelog file is actually updated on disk [...]

The `github.releaseNotes` script is only meant to override the output of `git.changelog` to represent the release notes for the GitHub Release. This also does not update any file.

So I guess the issue is that there is no auto-changelog command from any hook that updates the changelog file the way you want it? Then I'm afraid it would need to end up in a plugin (like [@release-it/conventional-changelog](https://www.npmjs.com/package/@release-it/conventional-changelog) or [@release-it/keep-a-changelog](https://www.npmjs.com/package/@release-it/keep-a-changelog)), which should provide the flexibility you need.

**Comment by mansona** [comment] 2021-03-26 14:38
Yea it does seem like a plugin is the way to go 🙈  I guess that's understandable and it makes sense that we should have a plugin for auto-changelog so we can do things like I'm describing in this issue.

Thanks for the guidance @webpro 🎉  I'll add the plugin writing to my list and let you know how I get on 👍

**Comment by webpro** [comment] 2021-03-26 16:00
That would be awesome, @mansona! Let me know if/when you need any help. Going to close this issue for now (also given that there is a work-around).

**Closed by webpro** 2021-03-26 16:00 UTC
