### ISSUE TITLE
Dont Works yarn test

### ISSUE THREAD

**Issue by JotaP13** [release-it/release-it#593] opened 2020-01-29 11:22 UTC
Hi, when i do release and in before:init option do the "yarn test" terminal becomes freeze and dont do the next steps.

My yarn version is 1.21.1
I do test with jest 24.9.0
The proyect is in Vue 2.6
My system is Windows 10

Thanks fo all.

**Comment by webpro** [comment] 2020-01-29 12:43
Sounds like a duplicate of #574. Please check my latest comment and see if that works for you. Thanks!

**Closed by webpro** 2020-01-29 12:43 UTC
