### ISSUE TITLE
ERROR Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by agung2001** [release-it/release-it#986] opened 2023-03-07 11:27 UTC
I got this error `ERROR Cannot read properties of null (reading 'toString')` when trying to run `npm run release`

here's my package.json config
```
{
  "name": "project",
  "description": "Project",
  "author": "Agung Sundoro",
  "license": "ISC",
  "version": "0.0.1",
  "scripts": {
    "release": "release-it --"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.3.0",
    "@commitlint/config-conventional": "^17.3.0",
    "@release-it/bumper": "^4.0.0",
    "@release-it/conventional-changelog": "^5.1.1",
    "release-it": "^15.5.1"
  }
}
```

any idea about the error?

**Comment by webpro** [comment] 2023-03-07 12:41
No, please see https://github.com/release-it/release-it/blob/main/README.md#troubleshooting--debugging

**Comment by agung2001** [comment] 2023-03-07 14:31
ok here's the verbose mode when I try to run it :

```
➜  project git:(master) npx release-it -VV
$ git rev-parse --abbrev-ref HEAD
master
$ git diff --quiet HEAD
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.master.remote
origin
$ git remote get-url origin
git@bitbucket.org:remote-project.git
$ git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=* --abbrev=0
fatal: No names found, cannot describe anything.
$ git symbolic-ref HEAD
refs/heads/master
$ git for-each-ref --format="%(upstream:short)" refs/heads/master
origin/master
ERROR Cannot read properties of null (reading 'toString')
```

**Comment by webpro** [comment] 2023-03-09 11:48
What's the full config of release-it and plugins?

I suspect the issue is coming from the bumper plugin.

**Comment by agung2001** [comment] 2023-03-11 10:31
oh yeah right man here's my release-it config and plugins that I use :

### package.json
```
{
  "name": "project",
  "description": "Project",
  "author": "Agung Sundoro",
  "license": "ISC",
  "version": "0.0.1",
  "scripts": {
    "release": "release-it --"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.3.0",
    "@commitlint/config-conventional": "^17.3.0",
    "@release-it/bumper": "^4.0.0",
    "@release-it/conventional-changelog": "^5.1.1",
    "release-it": "^15.5.1"
  }
}
```

### .release-it.json
```
{
  "git": {
    "requireBranch": "master",
    "commitMessage": "chore: release v${version}"
  },
  "github": {
    "release": false
  },
  "npm": {
    "publish": false
  },
  "plugins": {
    "@release-it/bumper": {
      "in": "src/config.js",
      "out": "src/config.js"
    },
    "@release-it/conventional-changelog": {
      "header": "# 📟 Changelog",
      "infile": "CHANGELOG.md",
      "preset": {
        "name": "conventionalcommits",
        "types": [
          {
            "type": "feat",
            "section": "Features"
          },
          {
            "type": "fix",
            "section": "Bug Fixes"
          },
          {}
        ]
      }
    }
  }
}
```

### src/config.js
```
export default {
	"name": "Project",
	"tagline": "project",
	"production": true,
	"version": "0.0.1"
}
```

**Comment by webpro** [comment] 2023-03-15 21:15
Dynamic `.js` files are not supported as `in` option to the bumper plugin. Please see https://github.com/release-it/bumper/blob/master/index.js, I'm going to close this ticket here.

**Closed by webpro** 2023-03-15 21:15 UTC
