### ISSUE TITLE
Listen to data child process

### ISSUE THREAD

**Issue by shaije** [release-it/release-it#726] opened 2021-01-13 12:20 UTC
Hi,
i am using before:bump hook with script that logs messages to terminal.
to be clear i am using jest testing platform inside before:bump hook.
i saw you are using the shelljs package, the problem is the logs of jest tests are logged only in the end of the process, instead of continuously logging to bash.
what is needed it to listen to data on child process and log it (i added image with the changes i made).

![image](https://user-images.githubusercontent.com/16086931/104451355-17fa1a00-55aa-11eb-84e9-d5e4beb76353.png)

i am using release-it version 14.0.3 on ubuntu

it would be great if someone of the contributors will update it on the next version

Thank you!

**Comment by webpro** [comment] 2021-01-17 10:35
Duplicate of #727

**Closed by webpro** 2021-01-17 10:35 UTC
