### ISSUE TITLE
Do I have to manually click the publish button?

### ISSUE THREAD

**Issue by xsj114** [release-it/release-it#932] opened 2022-08-11 09:14 UTC
Execute yarn release, but the web page will still pop up. Manually click the release button to publish successfully. Can you not click the manual button?
![Uploading 1660208777829.jpg…]()

**Comment by xsj114** [comment] 2022-08-11 09:15
![Uploading 1660208777829.jpg…]()

**Comment by xsj114** [comment] 2022-08-11 09:16
![1660208777829](https://user-images.githubusercontent.com/33807441/184101925-e6d15d4c-2f66-48a0-97c3-036176a4debe.jpg)

**Comment by webpro** [comment] 2022-08-11 09:23
https://github.com/release-it/release-it/blob/master/docs/github-releases.md

The `GITHUB_TOKEN` environment variable should be set and then you can leave this to the default setting, i.e. don't set this release-it option at all, it will read `GITHUB_TOKEN` automatically when set.

**Comment by xsj114** [comment] 2022-08-11 10:04
You mean my  GITHUB_TOKEN  Is  not set? But I really set it up.
![1660211935719](https://user-images.githubusercontent.com/33807441/184110449-7514a625-4732-4b63-bfb1-3b2a9b22cde1.jpg)

**Comment by webpro** [comment] 2022-08-24 07:30
That configuration looks fine. I don't know why it's not available when release-it runs. And I can't reproduce this issue on my end, "it works on my machine" and in the GitHub Actions tests too.

**Comment by webpro** [comment] 2022-08-31 06:02
Closing this issue as I think it's not an issue with release-it. Feel free to re-open if necessary.

**Closed by webpro** 2022-08-31 06:02 UTC
