### ISSUE TITLE
beta and alpha releases do not work

### ISSUE THREAD

**Issue by bmorales-broditec** [release-it/release-it#1089] opened 2024-03-18 21:18 UTC
Hello everyone,

I have configured this package for a new project, however I noticed that the alpha and beta releases no longer work as before.

Before:
```bash
1.0.0-alpha.0 # npm run alpha-release
1.0.0-alpha.1 # npm run alpha-release
1.0.0-beta.0 # npm run beta-release
1.0.0 # npm run release
```

Now:
```bash
1.0.0 # npm run alpha-release
2.0.0 # npm run alpha-release
3.0.0 # npm run beta-release
4.0.0 # npm run release
```

### My files

package.json
```json
"scripts": {
    "release": "dotenv release-it --",
    "beta-release": "dotenv release-it major --preRelease=beta",
    "alpha-release": "dotenv release-it preminor --preRelease=alpha"
  },
  "release-it": {
    "git": {
      "commitMessage": "chore: release v${version}"
    },
    "gitlab": {
      "release": true
    },
    "npm": {
      "publish": false
    },
    "plugins": {
      "@release-it/conventional-changelog": {
        "infile": "CHANGELOG.md",
        "preset": {
          "name": "conventionalcommits",
          "types": [
            {
              "type": "feat",
              "section": "Features"
            },
            {
              "type": "fix",
              "section": "Bug Fixes"
            }
          ]
        }
      }
    }
  },
  "devDependencies": {
    "@commitlint/cli": "^19.2.0",
    "@commitlint/config-conventional": "^19.1.0",
    "@release-it/conventional-changelog": "^8.0.1",
    "dotenv-cli": "^7.4.1",
    "release-it": "^17.1.1"
  }
```

commitlint.config.cjs
```javascript
echo "module.exports = {extends: ['@commitlint/config-conventional']}"
```

**Comment by webpro** [comment] 2024-03-19 07:22
> however I noticed that the alpha and beta releases no longer work as before.

What does "before" mean here?

**Comment by bmorales-broditec** [comment] 2024-03-19 14:28
@webpro Before means when I did `npm run beta-release` the version it generated was **_1.0.0-beta.1_**, but now it suggests **_3.0.0_** or **_3.0.0-0_**. I also have husky with other validations, but I don't know if that affects.

**Comment by webpro** [comment] 2024-03-19 14:33
> when I did [...], but now

I meant what version of release-it were you using? What's different about the environment/context you're working in that might cause the different behavior/outcome?

**Comment by bmorales-broditec** [comment] 2024-03-19 15:02
@webpro  The only difference I have seen compared to the other project is that the project is in a subfolder, for example:

The project that does suggest the version well to me
```
└── project-name
     ├── .env
     ├── .env.example
     ├── .gitignore
     └── README.md
```

Project I have problems with
```
└── project-container
     ├── project-name
     ├── .env
     ├── .gitignore
     └── README.md
```

Because the package versions are the same and I also removed husky to check the validation hooks are not affecting this part.

**Comment by webpro** [comment] 2024-04-05 09:04
OK, so "before" means a different project here.

Either way, I don't have enough information to say something meaningful. I'd like to suggest to read the docs carefully, e.g. this part about how release-it determines the next version: https://github.com/release-it/release-it?tab=readme-ov-file#latest-version

**Comment by webpro** [comment] 2024-05-08 07:11
Closing due to lack of info/reproducible case.

**Closed by webpro** 2024-05-08 07:11 UTC

**Comment by bmorales-broditec** [comment] 2024-05-17 20:01
Finally, modifying the release scripts, adding `--` to them, now it behaves as I mentioned.

```
"alpha-release": "dotenv -e=.env release-it -- preminor --preRelease=alpha",
"beta-release": "dotenv release-it -- major --preRelease=beta",
"release": "dotenv release-it --"
```
