### ISSUE TITLE
Says npm is not logged in when npm is definitely logged in

### ISSUE THREAD

**Issue by selfagency** [release-it/release-it#682] opened 2020-06-28 17:17 UTC
I am using release-it v13.6.3 on Mac OS v10.15.5 with npm v6.14.5 and Node v12.18.1.

When I attempt to run `npm run release`, it tells me that npm is not logged in. I know I am because I publish npm packages all the time. But just to be sure, I re-logged into npm but that did nothing.

So, then I created an `.npmrc` file in my package root and sourced a `.env` file with a new npm token before running release-it, like suggested in the docs for CI/CD configurations. I can verify that the token is available in the environment after sourcing the `.env` file. However, still, nothing:

```shell
gridjs-vue on  master [!] is 📦 v0.3.3 via ⬢ v12.18.1 on ☁️  us-east-1
❯ npm run release minor

> gridjs-vue@0.3.3 release /Users/daniel/code/gridjs-vue
> eval $(envkey-source) && release-it "minor"

ERROR Not authenticated with npm. Please `npm login` and try again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gridjs-vue@0.3.3 release: `eval $(envkey-source) && release-it "minor"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gridjs-vue@0.3.3 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniel/.npm/_logs/2020-06-28T17_08_17_433Z-debug.log
```

I've tried with both yarn and npm in both BASH and my normal shell, Fish. I'm stuck. Any help would be appreciated.

**Comment by webpro** [comment] 2020-06-28 19:25
Sorry to hear you wasted time on this. release-it does a `npm whoami` to verify the user is logged in. So I wonder why that doesn't work for you. What do you see with this debug prefix:

```
DEBUG=release-it:* release-it [...]
```

Note that `NPM_TOKEN` seems not to be used by `npm whoami` (see #675).

In any case, you could resort to use `--npm.skipChecks` to skip the auth check and registry ping (https://github.com/release-it/release-it/blob/master/docs/npm.md#prerequisite-checks).

**Comment by selfagency** [comment] 2020-06-28 20:38
```
❯ release-it patch
/Users/daniel/code/gridjs-vue/node_modules/got/dist/source/create.js:133
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/daniel/code/gridjs-vue/node_modules/got/dist/source/index.js:7:18)
```

**Comment by selfagency** [comment] 2020-06-28 20:45
It worked when I skipped the checks, thanks

**Comment by webpro** [comment] 2020-06-29 06:15
That error log indicates you're probably using a version of Node.js *before* v10.

Any chance you could run with the `DEBUG=release-it:* ` prefix in the environment with Node.js v12? I'd like to understand where the original issue came from.

**Comment by selfagency** [comment] 2020-06-30 22:52
I'm thinking my local nvm was just being weird. I switched to Volta and now things are fine. I'd have to switch back to debug it.

**Comment by webpro** [comment] 2020-07-01 11:45
OK well, then I'm closing this issue.

**Closed by webpro** 2020-07-01 11:45 UTC

**Comment by lucianomlima** [comment] 2020-09-18 15:44
I'm stuck with this. I can get my logged in account with `npm whoami` command and even using `--npm.skipChecks` I get auth error. =/
```sh
$ yarn release patch --npm.skipChecks           
yarn run v1.22.4
$ dotenv release-it patch --npm.skipChecks
ERROR Not authenticated with npm. Please `npm login` and try again.
Documentation: https://git.io/release-it-npm

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 luciano@Lucianos-MacBook-Pro  ...projects/repos/sanar-mobile-login   develop ✔ ⬆ 
$ npm whoami
sanar
```

Using with DEBUG
```sh
 luciano@Lucianos-MacBook-Pro  ...projects/repos/sanar-mobile-login   develop ✔ ⬆ 
$ DEBUG=release-it:* yarn release patch --npm.skipChecks          
yarn run v1.22.4
$ dotenv release-it patch --npm.skipChecks
  release-it:config {
  release-it:config   cosmiconfig: {
  release-it:config     config: {
  release-it:config       git: [Object],
  release-it:config       github: [Object],
  release-it:config       npm: [Object],
  release-it:config       plugins: [Object]
  release-it:config     },
  release-it:config     filepath: '/Users/luciano/projects/repos/sanar-mobile-login/.release-it.json'
  release-it:config   }
  release-it:config } +0ms
  release-it:config {
  release-it:config   system: { 'release-it': '14.0.3', node: 'v12.16.3', os: 'macOS Catalina' }
  release-it:config } +4ms
  release-it:config {
  release-it:config   _: [ 'patch' ],
  release-it:config   increment: 'patch',
  release-it:config   ci: false,
  release-it:config   git: {
  release-it:config     commitMessage: 'chore(release): release ${version}',
  release-it:config     tagName: 'v${version}',
  release-it:config     requireUpstream: false,
  release-it:config     changelog: 'git log --pretty=format:"* +1ms (%h)" ${from}...${to}',
  release-it:config     requireCleanWorkingDir: true,
  release-it:config     requireBranch: false,
  release-it:config     requireCommits: false,
  release-it:config     addUntrackedFiles: false,
  release-it:config     commit: true,
  release-it:config     commitArgs: [],
  release-it:config     tag: true,
  release-it:config     tagAnnotation: 'Release ${version}',
  release-it:config     tagArgs: [],
  release-it:config     push: true,
  release-it:config     pushArgs: [ '--follow-tags' ],
  release-it:config     pushRepo: ''
  release-it:config   },
  release-it:config   github: {
  release-it:config     release: true,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     preRelease: false,
  release-it:config     draft: false,
  release-it:config     tokenRef: 'GITHUB_TOKEN',
  release-it:config     assets: null,
  release-it:config     host: null,
  release-it:config     timeout: 0,
  release-it:config     proxy: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   npm: {
  release-it:config     publish: true,
  release-it:config     publishPath: '.',
  release-it:config     tag: null,
  release-it:config     otp: null,
  release-it:config     ignoreVersion: false,
  release-it:config     skipChecks: false,
  release-it:config     timeout: 10
  release-it:config   },
  release-it:config   plugins: { '@release-it/conventional-changelog': { preset: 'angular' } },
  release-it:config   hooks: {},
  release-it:config   gitlab: {
  release-it:config     release: false,
  release-it:config     releaseName: 'Release ${version}',
  release-it:config     releaseNotes: null,
  release-it:config     tokenRef: 'GITLAB_TOKEN',
  release-it:config     assets: null,
  release-it:config     origin: null,
  release-it:config     skipChecks: false
  release-it:config   },
  release-it:config   isUpdate: false,
  release-it:config   version: { increment: 'patch', isPreRelease: false, preReleaseId: undefined }
  release-it:config }
  release-it:config { 'conventional-changelog': { preset: 'angular' } } +118ms
  release-it:plugins {
  release-it:plugins   namespace: 'conventional-changelog',
  release-it:plugins   options: { preset: 'angular', tagName: 'v${version}' }
  release-it:plugins } +0ms
  release-it:plugins {
  release-it:plugins   namespace: 'github',
  release-it:plugins   options: {
  release-it:plugins     release: true,
  release-it:plugins     releaseName: 'Release ${version}',
  release-it:plugins     releaseNotes: null,
  release-it:plugins     preRelease: false,
  release-it:plugins     draft: false,
  release-it:plugins     tokenRef: 'GITHUB_TOKEN',
  release-it:plugins     assets: null,
  release-it:plugins     host: null,
  release-it:plugins     timeout: 0,
  release-it:plugins     proxy: null,
  release-it:plugins     skipChecks: false,
  release-it:plugins     tagName: 'v${version}',
  release-it:plugins     pushRepo: '',
  release-it:plugins     changelog: 'git log --pretty=format:"* +7ms (%h)" ${from}...${to}',
  release-it:plugins     isUpdate: false
  release-it:plugins   }
  release-it:plugins }
  release-it:plugins {
  release-it:plugins   namespace: 'npm',
  release-it:plugins   options: {
  release-it:plugins     publish: true,
  release-it:plugins     publishPath: '.',
  release-it:plugins     tag: null,
  release-it:plugins     otp: null,
  release-it:plugins     ignoreVersion: false,
  release-it:plugins     skipChecks: false,
  release-it:plugins     timeout: 10
  release-it:plugins   }
  release-it:plugins } +1ms
  release-it:plugins {
  release-it:plugins   namespace: 'git',
  release-it:plugins   options: {
  release-it:plugins     commitMessage: 'chore(release): release ${version}',
  release-it:plugins     tagName: 'v${version}',
  release-it:plugins     requireUpstream: false,
  release-it:plugins     changelog: 'git log --pretty=format:"* +2ms (%h)" ${from}...${to}',
  release-it:plugins     requireCleanWorkingDir: true,
  release-it:plugins     requireBranch: false,
  release-it:plugins     requireCommits: false,
  release-it:plugins     addUntrackedFiles: false,
  release-it:plugins     commit: true,
  release-it:plugins     commitArgs: [],
  release-it:plugins     tag: true,
  release-it:plugins     tagAnnotation: 'Release ${version}',
  release-it:plugins     tagArgs: [],
  release-it:plugins     push: true,
  release-it:plugins     pushArgs: [ '--follow-tags' ],
  release-it:plugins     pushRepo: '',
  release-it:plugins     isUpdate: false
  release-it:plugins   }
  release-it:plugins }
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 'v=1&tid=UA-108828841-1&cid=4ec25ab3-5df8-4ea5-a958-59ca32c71809&cd1=14.0.3&cd2=v12.16.3&cd3=macOS+Catalina&cd4=1&cd5=0&cd6=0&cd7=0&cd8=null&cd9=undefined&cd11=0&cd12=1&cd13=1&cd14=1&cd15=patch&cd16=0&t=event&ec=session&ea=start'
  release-it:metrics } +0ms
npm notice PING https://registry.yarnpkg.com/
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luciano/.npm/_logs/2020-09-18T15_43_36_368Z-debug.log
  release-it:shell {
  release-it:shell   command: 'npm whoami',
  release-it:shell   options: { write: false },
  release-it:shell   code: 1,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'npm ERR! code ENEEDAUTH\n' +
  release-it:shell     'npm ERR! need auth This command requires you to be logged in.\n' +
  release-it:shell     'npm ERR! need auth You need to authorize this machine using `npm adduser`\n' +
  release-it:shell     '\n' +
  release-it:shell     'npm ERR! A complete log of this run can be found in:\n' +
  release-it:shell     'npm ERR!     /Users/luciano/.npm/_logs/2020-09-18T15_43_36_368Z-debug.log\n'
  release-it:shell } +0ms
  release-it:npm Error: npm ERR! code ENEEDAUTH
  release-it:npm npm ERR! need auth This command requires you to be logged in.
  release-it:npm npm ERR! need auth You need to authorize this machine using `npm adduser`
  release-it:npm 
  release-it:npm npm ERR! A complete log of this run can be found in:
  release-it:npm npm ERR!     /Users/luciano/.npm/_logs/2020-09-18T15_43_36_368Z-debug.log
  release-it:npm 
  release-it:npm     at /Users/luciano/projects/repos/sanar-mobile-login/node_modules/release-it/lib/shell.js:69:18
  release-it:npm     at /Users/luciano/projects/repos/sanar-mobile-login/node_modules/shelljs/src/exec.js:127:9
  release-it:npm     at ChildProcess.exithandler (child_process.js:310:5)
  release-it:npm     at ChildProcess.emit (events.js:310:20)
  release-it:npm     at maybeClose (internal/child_process.js:1021:16)
  release-it:npm     at Socket.<anonymous> (internal/child_process.js:443:11)
  release-it:npm     at Socket.emit (events.js:310:20)
  release-it:npm     at Pipe.<anonymous> (net.js:672:12) +0ms
npm notice PONG 1.262ms
  release-it:shell {
  release-it:shell   command: 'npm ping',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '',
  release-it:shell   stderr: 'npm notice PING https://registry.yarnpkg.com/\nnpm notice PONG 1.262ms\n'
  release-it:shell } +1s
1.3.0
  release-it:shell {
  release-it:shell   command: 'npm show @sanar/mobile-login@latest version',
  release-it:shell   options: { write: false },
  release-it:shell   code: 0,
  release-it:shell   stdout: '1.3.0',
  release-it:shell   stderr: ''
  release-it:shell } +362ms
  release-it:metrics {
  release-it:metrics   url: 'http://www.google-analytics.com/collect',
  release-it:metrics   statusCode: 200,
  release-it:metrics   statusMessage: 'OK',
  release-it:metrics   payload: 't=exception&exd=Error%3A+Not+authenticated+with+npm.+Please+%60npm+login%60+and+try+again.'
  release-it:metrics } +2s
ERROR Not authenticated with npm. Please `npm login` and try again.
Documentation: https://git.io/release-it-npm

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lucianomlima** [comment] 2020-09-18 15:53
Change `.release-it.json` to following works for the npm checks
```json
  "npm": {
    "publish": true,
    "skipChecks": true
  },
```

But now I'm have another error. My package is scoped and private. When trying to release the patch
```sh
 luciano@Lucianos-MacBook-Pro  ...projects/repos/sanar-mobile-login   develop ✔ ⬆ 
$ yarn release patch
yarn run v1.22.4
$ dotenv release-it patch
ERROR Unable to fetch from git@github.com:sanar/sanar-mobile-login.git
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But I can run `yarn info` or `npm info` properly on terminal (I have SSH defined on terminal).

**Comment by webpro** [comment] 2020-09-18 15:55
- Looks like somehow the `.release-it.json` is over-ruling the command-line argument, which should definitely not happen. But at least you have a work-around now.
- You need a valid public key for the Git transport protocol, as release-it does a `git fetch` (and later e.g. `git push`)

**Comment by lucianomlima** [comment] 2020-09-18 15:58
@webpro I have a valid public key, but is protected by a password. Can this be the cause?

**Comment by webpro** [comment] 2020-09-18 16:00
Note sure. I wil try this myself when I have the time. Please open another issue if necessary. In the end release-it does `git fetch` and `git push` which you can test directly yourself.
