### ISSUE TITLE
Bug?: Patch releases that contain only chores, and empty changelog

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [release-it/release-it#964] opened 2022-12-24 16:49 UTC
Example: https://github.com/JoshuaKGoldberg/template-typescript-node-package/releases/tag/v1.27.6

The combination of automated dependency `chore` bumps and release-it will result in frequent releases that have no contents listed. In general, it looks like release-it is making releases when there's just one `chore` commit in the history.

This feels like a bug, but I'm not sure which solution is preferable:

* Skipping releases when there are only `chore`s
* Including chore messages in those releases

**Comment by webpro** [comment] 2023-01-05 15:14
The main thing here is probably that you're using the [conventional-changelog plugin](https://github.com/release-it/conventional-changelog), which delegates the changelog generation to the actual conventional-changelog-core and, in your case, conventional-changelog-commitlint packages.

As noted in the plugin docs, hopefully https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.1.0/README.md contains your answer.

This is likely not a bug in release-it, so I'm going to close this issue here, but feel free to open a new issue in the plugin or in the relevant packages.

**Closed by webpro** 2023-01-05 15:14 UTC

**Comment by JoshuaKGoldberg** [comment] 2023-01-06 01:29
Got it, thanks for the informative response!
