### ISSUE TITLE
ERR_ESM_REQUIRED when using CLI

### ISSUE THREAD

**Issue by beaugunderson** [release-it/release-it#1013] opened 2023-06-13 23:17 UTC
With latest:

```
node_modules/.bin/release-it
/Users/beau/p/meris-editor/node_modules/ansi-align/index.js:3
const stringWidth = require('string-width')
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/beau/p/meris-editor/node_modules/string-width/index.js from /Users/beau/p/meris-editor/node_modules/ansi-align/index.js not supported.
Instead change the require of /Users/beau/p/meris-editor/node_modules/string-width/index.js in /Users/beau/p/meris-editor/node_modules/ansi-align/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/ansi-align/index.js:3:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.0.0
```

With @^14:

```
node_modules/.bin/release-it
/Users/beau/p/meris-editor/node_modules/inquirer/lib/utils/screen-manager.js:8
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/beau/p/meris-editor/node_modules/strip-ansi/index.js from /Users/beau/p/meris-editor/node_modules/inquirer/lib/utils/screen-manager.js not supported.
Instead change the require of index.js in /Users/beau/p/meris-editor/node_modules/inquirer/lib/utils/screen-manager.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/inquirer/lib/utils/screen-manager.js:8:19)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/inquirer/lib/prompts/base.js:15:23)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/inquirer/lib/prompts/list.js:16:14)
    at promptModule.restoreDefaultPrompts (/Users/beau/p/meris-editor/node_modules/inquirer/lib/inquirer.js:61:33)
    at inquirer.createPromptModule (/Users/beau/p/meris-editor/node_modules/inquirer/lib/inquirer.js:72:16)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/inquirer/lib/inquirer.js:84:28)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/release-it/lib/prompt.js:1:18)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/release-it/lib/tasks.js:6:16)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/release-it/lib/index.js:2:18)
    at Object.<anonymous> (/Users/beau/p/meris-editor/node_modules/release-it/bin/release-it.js:6:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.0.0```

**Comment by beaugunderson** [comment] 2023-06-13 23:22
Interestingly if I `yarn global add` it works. The project I'm working on is a vite-react-ts-electron app, if that's useful.

**Comment by webpro** [comment] 2023-07-09 18:22
Is this still an issue? I'm not sure where to start looking for, are you sure it's an issue in release-it?

**Comment by platzhersh** [comment] 2023-09-18 13:44
I'm having the same issue. I think it is caused by `strip-ansi` requiring an older `string-width` version than some of my other packages (I had to add a resolution for string-width >6.1.0 in package.json before)

**Comment by platzhersh** [comment] 2023-09-18 16:01
@beaugunderson did that solve it for you? I think 6.1.0 is just not supported by align-ansi

**Comment by beaugunderson** [comment] 2023-09-18 18:37
yes, root cause is newer versions of those modules either moving to ESM
only or relying on modules that are ESM only

**Comment by platzhersh** [comment] 2023-09-18 20:01
Yeah, I wasn't able to solve it, `string-width` 6.1.0 seems to be incompatible with `ansi-align`, but I have other packages that are not compatible with `string-width` lower than 6.1.0

```
node_modules/ansi-align/index.js:3
const stringWidth = require('string-width')
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/string-width/index.js from node_modules/ansi-align/index.js not supported.
Instead change the require of node_modules/string-width/index.js in node_modules/ansi-align/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (node_modules/ansi-align/index.js:3:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.4.0
```

**Comment by webpro** [comment] 2024-05-08 07:25
Hopefully by now the latest versions of Node.js, release-it and updated dependencies I would expect this issue to be sorted. So I'm closing this issue, but feel free to discuss further or open a new issue.

**Closed by webpro** 2024-05-08 07:25 UTC

**Comment by GendelfLugansk** [comment] 2024-10-31 15:30
I encountered this problem as well. Sinse my project is electron+vite+react, using "resolutions" most probably will break something. Workaround that I applied is to remove release-it dependency and `npx` / `npm exec` instead

example with npm exec:

```
"scripts": {
    "release:alpha": "npm exec -q -- release-it --preRelease=alpha --only-version",
    "release:beta": "npm exec -q -- release-it --preRelease=beta --only-version",
    "release": "npm exec -q -- release-it --only-version"
  },
```
