### ISSUE TITLE
Use github releases without token

### ISSUE THREAD

**Issue by nordurljosahvida** [release-it/release-it#778] opened 2021-06-19 15:59 UTC
Using github config:

```
  "github": {
    "release": false,
    "releaseName": "Release ${version}",
    "releaseNotes": "Release ${version}",
    "preRelease": true,
    "draft": false,
    "tokenRef": "GITHUB_TOKEN",
    "assets": null,
    "host": null,
    "timeout": 0,
    "proxy": null,
    "skipChecks": false
```

No token, just ssh, everything works. If I enable `"release": true,`, token is requested:

```
ERROR Environment variable "GITHUB_TOKEN" is required for GitHub releases.
Documentation: https://git.io/release-it-github
```

How do I use github releases function without token?

I think the only thing that needs to be there for github to consider a tag also a release is a title, which shows as unpopulated with this config on github.com.

Thanks

**Comment by webpro** [comment] 2021-06-20 10:14
When you (or release-it) `git push` a tag to GitHub, it shows as an unpopulated release indeed.

However, to create an actual GitHub Release (including e.g. title and release notes), the GitHub REST API is used, and this requires the token.

**Comment by webpro** [comment] 2021-06-21 05:34
Maybe this is a duplicate of #749. Either way, I think this one can be closed.

**Closed by webpro** 2021-06-21 05:34 UTC

**Comment by webpro** [comment] 2021-06-28 07:16
Also see #749: https://github.com/release-it/release-it/blob/65001f54ae503ced6575c96cfbeddcb638d31760/docs/github-releases.md

Not released yet.

**Comment by webpro** [comment] 2021-08-08 10:02
This has been added in [v14.11.0](https://github.com/release-it/release-it/releases/tag/14.11.0)
